### PR TITLE
Don't raise TwilioRestException

### PR DESCRIPTION
**Pull request by vkurup**
A failure in one number currently causes the remainder of the batch to fail (and if using the DatabaseRouter, causes the entire batch to be retried, usually with the same results leading to duplicate messages for some identities).

This PR keeps track of the failures and returns that, so that the router can optionally do something about it (like mark the individual transmissions as errored in the case of the DatabaseRouter).

### CODE REVIEW

**Comment by mlavin** [comment]
I'm not sure I like the change in the api of `backend.send`. The current base/blocking router doesn't expect `send` to return anything.

**Comment by vkurup** [comment]
Colin and I came up with this solution on short notice. The idea was that we'd also update the DatabaseRouter to look at that return value to update the status of individual transmissions appropriately. I agree that its not a clean solution, but I couldn't figure out a way to mark some messages to be retried and some to never be retried, without using the return value. 

The most important part was to make sure that a failed message didn't cause the whole batch to be retried. As I'm typing, I'm thinking the proper fix is to make a change to the DatabaseRouter. Maybe get rid of the 'automatic retry'?

I'd appreciate any ideas :) BTW, we're currently using this branch for RescueSMS.

**Comment by mlavin** [comment]
Based on our discussion, the way to move this forward is to make `failed_identities` part of the exception rather than the return value which is thrown away by RapidSMS. RapidSMS would still need allow the exception information to propagate up which it currently does not. Opening a related RapidSMS case to propose this to be added to the router/backend API.

**Comment by vkurup** [comment]
This has been updated to work with the latest RapidSMS API that allows failed_identities to be attached to the exception.

**Pull request merged**
