### PR TITLE
Python 3 Support

### PR DESCRIPTION
**Pull request by lsgunth**
The only change necessary seems to be removing 4 'u' prefixes. 

Thanks,

### CODE REVIEW

**Comment by lsgunth** [comment]
I'd have added environments to the CI build but rapidsms hasn't done a python 3 release yet.

**Comment by mlavin** [comment]
I don't think the plan was to support  < 3.3 and these unicode literals are valid in 3.3+. These South migration files are also going to be removed In #16 when Django 1.6 support is dropped. If there aren't any other changes then I think this can be closed.

**Comment by lsgunth** [comment]
Thanks, though I'm currently running python 3.2 as that is what's in Debian Stable. So if you're going to drop the migration I'm happy with it. I just would like it to run on 3.2  without having to maintain my own fork.

**Comment by mlavin** [comment]
#16 has handled meaning this migrations no longer exist and I'm going to close this. Thank you again for your contribution.

**Pull request closed without merging**
